### ISSUE TITLE
Private game lookup

### ISSUE THREAD

**Issue by JorenC** [zond/dipact#100]
- We need to add a place where the game ID can be found (I'd say in the metadata dialog)

- We need to add an empty search result of game lookup failed

- We need to add the place to find the ID in the lookup dialog

**Comment by zond** [comment]
Oh, I see that I never actually finished this dialog. Embarrasing.

**Comment by zond** [comment]
It sort of works now. WDYT?

**Comment by zond** [comment]
I think it works. Reopen if not.
