### ISSUE TITLE
Nation avatar improvements

### ISSUE THREAD

**Issue by zond** [zond/dipact#105]
Like we have dialogs for users (opening when the user avatar is clicked) we should have them for nations (opening when the nation avatar is clicked). It should maybe only contain the mute option, but that would be quite useful.

Also, I want a badge on the nation avatar if it's muted, to make it clear who's muted.

**Comment by JorenC** [comment]
Very good idea!
I can work in a muted avatar state

Codesandbox is here; https://codesandbox.io/s/chatavatars-r30yl?file=/src/App.js

**Comment by JorenC** [comment]
If any question, let me know. I think the challenge will be adjusting the font size in the small 12px avatars, but materialUI should be able to render small avatars

**Comment by zond** [comment]
Fixed, sort of. Reopen if the styling needs more fixing, or anything like that.
