### ISSUE TITLE
Join/Leave button from staging game.js

### ISSUE THREAD

**Issue by JorenC** [zond/dipact#106]
People copy the game link (or click the game list view after joining a game) and enter game.js. 

A) there is a game, but no indication that the game is still staging.
B) there is no option to join the game - if there is an easy way to join the game here, you can just invite friends to (private) games by just copying the link and letting them open it
C) there is no easy way to leave. If you joined the wrong game and enter via the "start -> my staging" list view, there is no leave option. You need to go to the side menu, click "my staging" and there are the expand views. This was known issue from the start but too much time to fix for current state of start.js.

Creating an app bar (rather than snackbar) in the game view for staging games saying "This game is waiting for enough players JOIN/LEAVE" would solve most of the issues.

**Comment by zond** [comment]
Ah, this makes a lot of sense.
