### ISSUE TITLE
User avatar improvement

### ISSUE THREAD

**Issue by zond** [zond/dipact#107]
The user meta data dialog opened by the user avatar should have a ban checkbox.

**Comment by zond** [comment]
@JorenC do we also want a "banned badge" if the user is banned? To remind people of who they have banned and reduce feelings of "hm, why do I never play with that guy anymore?" after accidentally banning someone.

**Comment by JorenC** [comment]
I doubt they will have a "why don't I play with him anymore". But we could
look at a banned image, I'd say we do something over the avatar..

**Comment by zond** [comment]
My fear is that the banning system is so transparent. You won't see the one you banned anymore in new games, but other than that it doesn't make any noise.
