### ISSUE TITLE
Build phase instructions

### ISSUE THREAD

**Issue by JorenC** [zond/dipact#113]
For new players, the "no orders confirmed" toast should change into "you may build X units" or "you need to remove X units".

We might also want to think about whether we allow a user to build more than he/she is allowed. Now, it's not clear which order would fail if there are too many.

I'd say we don't allow people to build more than they are allowed and help.

**Comment by zond** [comment]
Yeah, a better instruction is good.

It IS actually defined which orders fail - godip follows DATC, and the recommendations by Kruijswijk. See   http://web.inter.nl.net/users/L.B.Kruijswijk/#4.D.4

We might block them from building too much, yeah.

**Comment by zond** [comment]
We have the instructions now, but not the limitations which I think is a good feature as well - however, it requires some new concepts all the way down in the adjudicator, so it's a bit messier.

**Comment by zond** [comment]
I'll close this for now - we have the instructions, at least.
