### ISSUE TITLE
Show phase balance

### ISSUE THREAD

**Issue by zond** [zond/dipact#134]
Number of SCs, number of builds, etc

**Comment by zond** [comment]
@JorenC do you know where this would work? Maybe in the Players dialog?

**Comment by JorenC** [comment]
I think this should be on the order screen. During a current phase you only see your own (orders, units, SCs) but you can see all for other units... Maybe?

**Comment by zond** [comment]
But people want it for the current phase, i.e. who is bigger or close to solo... How to show that in the orders view intuitively?
