### ISSUE TITLE
After a game is finished, 99+ unread messages

### ISSUE THREAD

**Issue by JorenC** [zond/dipact#138]
When a game is finished and all messages become public, there is a 99+ unread message counter, for all messages that are released of which the player was not part of the game.

Ideally, we would:
- Send one public message in the Diplicity channel (OttoHead) that the game is over, with the game result. Also older players already out of the game will receive this as a notification (sort of "what happened with the game?" And honour for the winners). This will show a new notification enticing the player to check out the game.

- any new messages sent to a channel OF WHICH THE CURRENT PLAYER IS A MEMBER appear as "new messages" with their own counter.

- any (old and new) messages OF A CHANNEL OF WHICH THE PLAYER IS NOT A MEMBER never receive an unread badge - they are for background info only, and the Diplicity message (above), also tells the player messages are now public that is enough enticement

**Comment by zond** [comment]
https://github.com/zond/diplicity/issues/153 will fix the unread messages counters.

**Comment by zond** [comment]
It's not fixed yet though, and the other stuff you wrote about aren't covered by it, so feel free to keep it open..
