### ISSUE TITLE
Better e-mail messages 

### ISSUE THREAD

**Issue by JorenC** [zond/dipact#143]
These messages are not really -human- readable.

Is there any way that we can use an <a> link in the e-mail and use actual text? 

![image](https://user-images.githubusercontent.com/7293081/82727434-d6e78980-9cea-11ea-9c41-0eeb9e6a8f8b.png)

**Comment by zond** [comment]
The email sending thing does support html email, but the hassle of getting those through spam filters doesn't really make them worth it IMO

**Comment by JorenC** [comment]
True.

Where are they defined?
Can I change the text anyway?

I think with some spacing and separating of content, we can already change
a bit.

**Comment by zond** [comment]
They are defined around https ://github.com/zond/dipact/blob/master/resources/js/settings_dialog.js#L386, contain only the body, the unsubscribe link, and the view link.
