### ISSUE TITLE
There is no indicator a touch worked when supporting/convoying

### ISSUE THREAD

**Issue by JorenC** [zond/dipact#148]
When moving units, you can see that your tap has been registered, because the highlighted areas change. 

When selecting "support" or "convoy", when pressing the unit you want to convoy is often not clear, because the same regions stay highlighted. It could mean that there is (a) a misclick or (b) it didn't register or (c) it registered but no feedback. When you tap again, it becomes a hold order. 

I think we should add some "order builder". I'm thinking a snackbar on the bottom of the screen that builds with what you selected

Press army munich
Press support
Snackbar "Munich supports ..."
Press Ruhr
Snackbar "Munich supports Ruhr to ..."
Press Burgundy
Snackbar "Munich supports Ruhr to Burgundy" until order is saved and dispayed on map

Press army Munich
Press move
Snackbar "Munich moves to..."
Press Ruhr
Snackbar "Munich moves to Ruhr" until order is saved and displayed on map.

What do you think?

**Comment by zond** [comment]
I have something that does this. It was unexpectedly hard, and it doesn't look exactly like you asked, but I'll close it for now.
