### ISSUE TITLE
[UX] Order menu hints

### ISSUE THREAD

**Issue by JorenC** [zond/dipact#149]
Order results (OK, ErrBounce) are computer, not human language.
Order inconsistency warnings are not clear enough yet.

@zond I guess this might also mean a change in godip? 
Maybe I can already just change "ErrBounce: " into something like "Bounced with: " in godip?

**Comment by zond** [comment]
What you get from godip is codes, that we expect the client to map to human readable messages, so I'd suggest creating/improving such mappings in dipact.

**Comment by JorenC** [comment]
I've completed this, keep eye open for any codes missed
