### ISSUE TITLE
Finished game white screen

### ISSUE THREAD

**Issue by AceboneV2** [zond/dipact#152]
When trying to view a finished game, the app will white screen as shown here:

https://youtu.be/t9pikWSA1iw

**Comment by zond** [comment]
Solved now. All finished games are now considered as having passed the "everyone is ready"-state, and will now have the nations of their players published (to avoid people skipping out in the "get ready"-state when they get Austria again, we censor nations during the "everyone is ready"-state.

My first fix managed to break ~60 old games before I realised what was happening, so I had to build a _new_ fix to repair that before continuing to fix this one :O
