### ISSUE TITLE
[Bug] Mustering

### ISSUE THREAD

**Issue by JorenC** [zond/dipact#154]
1) Do we now include mustering? Or is this leftover code from yesterday?
![image](https://user-images.githubusercontent.com/7293081/83338389-2ff38680-a2c4-11ea-86ab-6573539d37ef.png)

2) If we do, it needs to have a checkbox option in the create game dialog (with explanation).
2a) If we do, I think we need to (quickly) implement a better version in dipact:
-> A big "READY" button on the game list in start.js
-> A big "READY" button on a dialog when opening the game

3) I made a test game (checking the order list errors). After "mustering" with both users, the system sends a message that the game is really starting, but I still can't place orders - even though the phase is Sprint/Movement..

![image](https://user-images.githubusercontent.com/7293081/83338397-3e41a280-a2c4-11ea-8839-99ac42dc5411.png)
![image](https://user-images.githubusercontent.com/7293081/83338402-4d285500-a2c4-11ea-9aa7-58195689a07f.png)

**Comment by zond** [comment]
Yes - the whole shitshow yesterday was because I accidentally released the mustering feature :/

**Comment by JorenC** [comment]
![image](https://user-images.githubusercontent.com/7293081/83338415-7517b880-a2c4-11ea-8ecc-23ae719a6f46.png)

I'm supposed to be Russia, but I can't make any movements.

**Comment by JorenC** [comment]
Update: 
A reload and re-logging in allowed me to make orders. HOWEVER, when using diplicity.com, the "confirm order" bar was completely gone. Another reload had that fixed - but something to track. Just a glitch or muster-related (the same thing we'll be asking ourselves for another 3 weeks)
![image](https://user-images.githubusercontent.com/7293081/83338462-efe0d380-a2c4-11ea-801a-86e1fe09cf63.png)

**Comment by zond** [comment]
The game should be fine to play after all players check ready (within a few seconds) - reload should be fine.

I now added code to the server that sends a "new phase notification", which is basically just a "this game has changed state", to the clients whenever the game ends mustering state - either by being reset or by starting for real.

Yes, we also need to add buttons for READY. I'll start on that now.

**Comment by zond** [comment]
I have now added a big button in the game list element to allow players to mark ready from there. I have also made the "you haven't marked ready"-snackbar in the game also mention that the game won't start until everyone has marked as ready, but I guess a dialog would be better here, but this was a quick fix.

**Comment by JorenC** [comment]
So I think the solution is easy, the implementation is not.

When a game has enough players, start a "phase 0", during which chat is not yet available.
Send each a "new phase" notification in which they are alerted that the game begins. This notification will tell them that they need to submit orders to confirm they're playing
Players clicking the notification will enter the gameview
All players entering the game view during this time will get to see a dialog with a welcome to the game, and have them ask to confirm they're playing.
https://material-ui.com/components/dialogs/
Once they confirmed they enter the gameview as normal, similar to staging games.
Once all players have confirmed, start the new phase (spring 1901).
If some players have not confirmed, move back to open and send everyone a notification that the game will move back to the staging area.

**Comment by zond** [comment]
That last comment is just a copy from the original issue, right?

**Comment by JorenC** [comment]
Yes

**Comment by zond** [comment]
By the way - I'd love to roll this out for real and properly :)

What do we need to do for you to be happy with that?

**Comment by zond** [comment]
@JorenC what do we need to do for you to be happy with opening this up publically?
