### ISSUE TITLE
After Lab mode is started, application slows to a crawl..

### ISSUE THREAD

**Issue by JorenC** [zond/dipact#166]
Opening lab mode makes the app much slower.
However, even after disabling lab mode, the app takes ~5 seconds to just open the 'more" (three dots) menu. 

I think there is some memory leak, or some elements that are not removed from memory. But now we REALLY are approaching a level I don't know.

**Comment by zond** [comment]
Can you tell me a reliable way to repro this?

When I try it, the app is as slow before as after?

**Comment by JorenC** [comment]
I'm working on it now. It might be a placebo effect - I'll keep an eye out. 

Please don't touch lab mode for a couple of days until I finish my commit. I will need some help though, but I'm not done tonight

**Comment by JorenC** [comment]
I'll close it for now
