### ISSUE TITLE
Customise the map clicks

### ISSUE THREAD

**Issue by zond** [zond/dipact#171]
I just moved the dippymap.js map-mutation/event handling library into the client (the server still has it's own version, used by e.g. the old client, and the server map URLs.

This means that we can start experimenting with requiring longer clicks or other things for our map handling.

Examples:

- Longer clicks for info popups (something @JorenC wanted).
- Highlight provinces somehow on touchStart so that they feel more like buttons.

**Comment by zond** [comment]
@JorenC do you have any ideas in particular about how you want the click handling changed?

**Comment by JorenC** [comment]
Close as legacy
