### ISSUE TITLE
Game Settings in Game.js

### ISSUE THREAD

**Issue by zond** [zond/dipact#175]
Now that only staging games (iirc) have the expandable view in "My Games", it's hard to find out how to rename my started or my finished games - since that button was in the expanded view of the game list element.

@JorenC, where do you think that button should go now? Or should we make started and finishes games in the "My Games" view also expandable?

**Comment by JorenC** [comment]
We need a "game settings" option in the overflow menu of game.js.

Then, we can show everything we normally show in the expanded game view.

**Comment by JorenC** [comment]
if game is not started, should be called "invite" and link copied snackbar should say: "send link to friend"
invite should be a button on the main overview page, e.g. leave/join/view/rename

**Comment by JorenC** [comment]
This screen should also have the variant rules same as on the create new game

**Comment by JorenC** [comment]
@zond AFAIK there is no 'rename' button. Either way, we can close this - I think? Feel free to reopen.
