### ISSUE TITLE
Lab mode slows down

### ISSUE THREAD

**Issue by JorenC** [zond/dipact#185]
As a joke I wanted to make a screen with ALL territories of the new cold war map filled with NATO units only.

After adding about the sixth unit, the whole application froze (Android). Trying on diplicity.com did the same thing.

It seems there is something adding to memory when expanding from the default state? It feels like it shouldn't be heavier on the app, since it can handle many units easily in "normal" mode... I think it's something to do with how it keeps data in memory?

![Screenshot_2020-06-22-20-28-25-858_com android chrome](https://user-images.githubusercontent.com/7293081/85330776-511b5180-b4d5-11ea-8cc3-4418d3c180c5.jpg)

**Comment by zond** [comment]
Thanks! That gives a bit of a hint about where to look for the memory leak!

**Comment by JorenC** [comment]
duplicate of https://github.com/zond/dipact/issues/268
