### ISSUE TITLE
PanZoom ticks

### ISSUE THREAD

**Issue by JorenC** [zond/dipact#189]
So I love the new panzoom, and I like that you've added the "double tap to zoom in feature". However, there's an issue.

1) It's discrete - even though the old panzoom would have a discrete end and start position, the zoom in feature was an animation. This is the same behaviour that happens when you double tap on a normal (zoomable) Chrome page. The discrete one feels jointed and worse. 

2) The discreteness becomes a bigger problem on desktop. When you scroll with a mouse which has ticks in the scrollwheel (as do I.. do all mice?), this is tick 1: 
![image](https://user-images.githubusercontent.com/7293081/85627130-58c22e00-b66e-11ea-844d-d6011d90168b.png)

This, however, is tick 2:
![image](https://user-images.githubusercontent.com/7293081/85627453-cc643b00-b66e-11ea-812b-2d4a768f00c0.png)

Because of the discrete zoom levels, it's not possible to zoom in to the right level. When I use two finger pitch zoom on my touchscreen (I have a detachable tablet/desktop combination), I can zoom perfectly normal...
Before, I could scroll the mouse at a much more detailed level...

**Comment by zond** [comment]
You can still zoom with the scroll wheel, and it's more smooth than double click.

**Comment by zond** [comment]
But yeah, an animation might be good. I'll see if I can make it so.

**Comment by zond** [comment]
Alright, this is much smoother now. Please verify :)

**Comment by zond** [comment]
(In beta, that is)

**Comment by zond** [comment]
Reopen if it doesn't work as you want
