### ISSUE TITLE
Make the About page a bit nicer

### ISSUE THREAD

**Issue by zond** [zond/dipact#201]
I just added an "About" option in the main menu describing the game a bit more for beginners.

@JorenC, please take a look and see what you want to change when you have the time?

**Comment by JorenC** [comment]
Hi Martin,

In beta-dot-dipact I don't see the about page. 
Where can I find it

**Comment by zond** [comment]
![Screenshot_20200910-094833](https://user-images.githubusercontent.com/7541/92696892-df6fd880-f34a-11ea-9a6a-3376825ce830.png)

Top of the menu :)

**Comment by zond** [comment]
Have you seen the new about page?

**Comment by JorenC** [comment]
I've updated and rewritten the about page. Fixed in the beta branch.
