### ISSUE TITLE
Sandbox mode: adding armies on coasts

### ISSUE THREAD

**Issue by jensforsgard** [zond/dipact#204]
In sandbox mode, if you wish to add an army to Spain, then it will appear either on the North Coast or on the South Coast. 

![Screen Shot 2020-10-19 at 8 30 09 AM](https://user-images.githubusercontent.com/45589586/96457842-dd205a00-11e5-11eb-8b1e-86d1504d1993.png)

This army cannot be removed.

This army can only receive a hold order.

![Screen Shot 2020-10-19 at 8 30 57 AM](https://user-images.githubusercontent.com/45589586/96458169-3be5d380-11e6-11eb-9394-9fc1cab276f5.png)

**Comment by zond** [comment]
Should be fixed in https://github.com/zond/dipact/commit/4c73ff84d4b04d4ea695c035e09f562a7770dce1
