### ISSUE TITLE
Feedback from Jerome

### ISSUE THREAD

**Issue by zond** [zond/dipact#208]
Jerome in Discord provided the following feedback:

Hey, I used the web version of simplicity for a few hours, and I have some feedback:

First of all, I have to say that the maps are absolutely gorgeous. Having dotted lines for support would make them perfect.
Here are the things that could be improved:
- [x] I don't understand what "Game mastered games" is.
 Joren to make a better approach. It needs some explanation, but also exploration as to what it actually does.

- [ ] I find the home page hard to read:
   - [ ] when it's empty, it's confusing, was there a message saying "you have no on-going game" or nothing at all? I don't remember, but having something more explicit would have helped (like: your on-going games will appear here when you join games)
_JOREN: I THINK this is about Game Mastered games. The 'My games' screen already shows the "foot soldiers" welcome page. The other ones (public/started/completed) are always visible. Indeed, we either want to NOT show a screen or show some sort of empty screen message. 

I see two solutions:
1. Add empty screen messages (no games). :( not cool.
2. Make one tab "My game master games" which is similar to the "My games" screen (combination of all, with VIEW ALL option to go to the dedicated screens. Then, remove the three "My game mastered games" from the side menu - you don't need them actually._

   - [x] information is split between left side info and right side info, with a huge amount of white space between the 2. I think all the info should be together.
   _JOREN: This is a bug. Should be max-width 940px on the container, margin-auto to left/right._
   - [x] there are lines to separate games, but not to separate sections, so there is no separator between the last ongoing game and the first forming game. I think there should be lines everywhere, and even bigger lines between sections. Another option is to have a different background for the section titles
  _JOREN: I'd say leave this. Not ideal, but less issue with the games. You generally know the games you're in. Creates clutter._
   - [ ] there is no status about the game: for each player, number of supply centers / number of supply centers to win
   _JOREN: If on the game list page, not enough space (mobile). We might want to make more 'tutorial' to explain where all the other options are in the game  > overflow menu, as it is in "scores"._
   - [x] there is no info about the rules of a given game, the only way to see the specifics of the rules for this game is to go to "new game", then "create game", then select the same variant. That's very far away
   _JOREN: Ideally, the game>overflow menu has an item with "variant rules", explaining the rules. This was the last thing I looked at before I 'left'. _
- [ ] I find the "open games" page hard to read:
   - [x] it has the same issues as the home page
   _Agreed on the 940px._
   - [ ] it needs a way to sort games (by players, by variant, ...) or filter games. When there are more than 50 games, it's hard to find the right one.
   _Yes, I think filtering would be very nice - especially now that we have the languages. This is also an annoyance for me for a while, but too much development effort is in this. If Martin is up for this, I"m happy to help._

**Comment by tttppp** [comment]
> when it's empty, it's confusing, was there a message saying "you have no on-going game" or nothing at all? I don't remember, but having something more explicit would have helped (like: your on-going games will appear here when you join games)
_JOREN: I THINK this is about Game Mastered games.

I find this about the "My Games" page. There's a New Game button at the bottom, but most of the page is games that I've finished. I'd expect to see games I can join when logging in, but I may not be a typical user.

**Comment by JorenC** [comment]
Hey @zond, I didn't receive any notification on this. Please make sure to @ me. 
Also, I'm planning to look at GM mode in the near future (see my 'wall of text' from earlier)... We could consider the grace period and look at other features real tourney organisers look at/need, to ensure it gets used.

**Comment by zond** [comment]
There's a lot to do :D

**Comment by JorenC** [comment]
- Explained GM games at least enough to show whether it's relevant
- Home page needs more details. Fixed the separate GM page.
- No SC/SC to win details. => It's in the more menu. Hopefully the settings menu helps findability (:/). In the future, I can expect a 'advanced view' for review purposes, where it would be added to the group below. Added variant rules.
- Added 'Game & Player info" > "Variant rules" to the settings info. Might be too hidden (vs 'variant rules' entry), but at least has a trail towards it.
- Filters TBD, huge item, has a separate issue. 

I'll close this for now, as we've likely addressed what we can, rest is in planning.
