### ISSUE TITLE
After deleting a game it's still in the list

### ISSUE THREAD

**Issue by JeromeA** [zond/dipact#213]
Steps to reproduce:
- create a private mastered game
- go to mastered game / staging game
- click delete
The game is still shown in the list, making it unclear whether the game was deleted or not. It should either be hidden, or (if it's on purpose) It should say "Deleted" somewhere in a very prominent way.

When refreshing the page, the game is not shown anymore.

**Comment by zond** [comment]
@JorenC I fixed the most important bit of this by adding a red 'Deleted' in the game list element view. I suspect you want it to look prettier though, so here's where it's defined: https://github.com/zond/dipact/blob/master/resources/js/game_list_element.js#L1057

**Comment by JorenC** [comment]
Hi Martin,

This solution works. 
Can we not, after the deleting, force update the "my staging game master' list with something like this.forceUpdate() ?

**Comment by zond** [comment]
There were problems with removing it, I remember (I started out with that solution). Maybe there were too many notifications and events and things connected to the element.
Anyway, I realized I kind of liked having it still present, so you could see what it was you removed. It felt less jarring somehow ;D
