### ISSUE TITLE
The defaults should be the recommended ones

### ISSUE THREAD

**Issue by JeromeA** [zond/dipact#214]
When creating a new private game, a message in red recommends "to not add requirements, so your friends can all join your game."

But Reliability is still marked as "important" and is checked by default, making the messaging ambiguous. Would it be possible not to check it at least?

**Comment by JorenC** [comment]
Agreed, unchecking by default in private game makes a lot of sense.

**Comment by zond** [comment]
Should be live in a few minutes.
