### ISSUE TITLE
Adjustment phase only working for one player in Sandbox

### ISSUE THREAD

**Issue by JeromeA** [zond/dipact#216]
Steps to reproduce:
- create a private mastered game France/Austria
- view it
- Marseilles moves to Spain
- Play as Austria
- Trieste moves to Venice
- Execute movements
- Execute retreats
- Execute movements
- Execute retreats
- Build an army in Trieste
- Play as France
It's not possible to build an Army as France.

When moving to a different date and back to adjustment phase, everything works again.

**Comment by JeromeA** [comment]
Actually the workaround doesn't work: after coming back to the adjustment phase, selecting a player, and adjusting, it's not possible to select another player, and moving back and forth to a different date clears the existing orders.

**Comment by zond** [comment]
Fixed in https://github.com/zond/dipact/commit/a48371bfd89012b72b231ab8cd74d2a8a871566c. Should roll out any minute.
