### ISSUE TITLE
Export game as animated gif

### ISSUE THREAD

**Issue by zond** [zond/dipact#23]
- Using something like https://jsfiddle.net/Wijmo5/h2L3gw88/ one can render an SVG to a canvas.
- Using https://github.com/yahoo/gifshot one can create a gif using a bunch of images.
- ...
- Profit!

**Comment by zond** [comment]
This feels like a gimmick - will it provide an actual benefit? Do we want to do it?

**Comment by JorenC** [comment]
I think it's not necessary.

Maybe in the long-long run.
Actually, a gif would not be timed, so I think the benefit is really
limited.

**Comment by zond** [comment]
Then I'll close it. Feel free to reopen :)
