### ISSUE TITLE
Separate styling from rendering logic and leverage theme more

### ISSUE THREAD

**Issue by johnpooch** [zond/dipact#232]
We are currently using a log of inline styling which is a bad practice. We should separate styling from the rendering logic. This reduces duplication and makes components easier to understand.

Additionally, material-ui provides `theme.spacing` which is very powerful. We should be using this everywhere instead of hard-coding spacing. Same with `theme.palette`

**Comment by JorenC** [comment]
Maybe we could set up a session where you explain to me how to use theme styling, as I'm completely in the blank. I know what it is as I've read material-ui extensively, but I can't get to use this properly....
