### ISSUE TITLE
Separate user-facing copy from components

### ISSUE THREAD

**Issue by johnpooch** [zond/dipact#239]
Blocks of user-facing copy should be separated from rendering logic. This makes components easier to understand and makes editing copy easier. Additionally, this makes sharing copy between react and react native easier.

**Comment by JorenC** [comment]
And it makes it easier to translate!

**Comment by JorenC** [comment]
@johnpooch this is something that I can really easily boyscout, but can you teach me the basics - where do I put the strings?

I often see things like
<Typography>
{explainerString}
</Typography>

but this explainerString is somewhere defined - I guess one separate 'content.js' page or something. 

Either way, this is something I can boyscout. Coding is harder for me.

**Comment by johnpooch** [comment]
Hey @JorenC so what I'm thinking is that copy will live in the `common` package which will be shared between react and react native. I'll show you an example of that so you can help out with that transition. but for now don't worry about it. Just gotta get initial common package set up done first
