### ISSUE TITLE
Fix issue with approved-frontend

### ISSUE THREAD

**Issue by johnpooch** [zond/dipact#243]
When a user logs in to the site for the first time in a dev environment, we get an error from the service because the client is not recognised.

**Comment by zond** [comment]
This is because the client doesn't accept a POST to the URL the browser ends up at.

![image](https://user-images.githubusercontent.com/7541/126290377-7ee2f5b4-783d-43b4-9670-b64b141785a9.png)

**Comment by zond** [comment]
[localhost.har.gz](https://github.com/zond/dipact/files/6846809/localhost.har.gz)

Here's a .har file for the failed redirect. Upload it in the network tab of Chrome.

**Comment by zond** [comment]
Is now fixed with new server side login flow.
