### ISSUE TITLE
Bad replacement of `scopedClass` leads to wrong icon sizes

### ISSUE THREAD

**Issue by zond** [zond/dipact#254]
A lot of React styling is only possible to do via the `classes` attribute, that assigns CSS classes to generated tags inside the React code.

`scopedClass` did this inline (which I kind of like, since styling is close to actual code - some people probably dislike it and I have on judgement :D )

Removing `scopedClass` and replacing it with just `style`-attributes on the React tags therefore doesn't work. Either something like `scopedClass` is needed, or adding new classes in the CSS manually.

Example (Notice the first icon with the check mark):

![image](https://user-images.githubusercontent.com/7541/128686332-6981e884-5590-4a9b-8839-7d02dca50370.png)

**Comment by zond** [comment]
Here's another example, I suspect.

Current master branch:
![image](https://user-images.githubusercontent.com/7541/129868688-9594e947-ed49-4796-9f5a-8ef44a50cb9a.png)

Current 'regular react app'-branch:
![image](https://user-images.githubusercontent.com/7541/129868797-5f2f5db7-fddf-43b2-b3c8-1d7c5310c113.png)

**Comment by johnpooch** [comment]
Resolved
