### ISSUE TITLE
Map not panning

### ISSUE THREAD

**Issue by JorenC** [zond/dipact#269]
Just experienced this bug that I heard others talk about as well. 
Map was stuck in bottom half, I could pan but not move it higher than this:
![image](https://user-images.githubusercontent.com/7293081/130859275-b1bb1eac-ef9b-47b7-bfde-05aa2a8050bc.png)

When the map was moving (normally the zoom image), it showed me a 'broken link' image:
![image](https://user-images.githubusercontent.com/7293081/130859226-ddbb287c-4434-4833-b3a6-deca9d4b12c0.png)

Console:
![image](https://user-images.githubusercontent.com/7293081/130859456-a075e7a9-bfd6-4ea0-b8bd-23b157f6661c.png)
I didn't see anything on the network tab.

This game:
https://beta.diplicity.com/Game/ahJzfmRpcGxpY2l0eS1lbmdpbmVyEQsSBEdhbWUYgICA95HnpQkM

A reload fixed it, can't reproduce... Still logged it. Feel free to close if this is all the info you can get out of it and it's not enough for next person who reports it.

**Comment by JorenC** [comment]
I keep getting this bug super regularly. Often it starts out okay and then loads a turn or something and turns into this

**Comment by zond** [comment]
Found a way to repro yet?
