### ISSUE TITLE
Grace period

### ISSUE THREAD

**Issue by JorenC** [zond/dipact#274]
The Nexus tournament organisers told me they didn't really consider diplicity because it has no GM mode (I told them it does now!). Another major blocker for using dippy for tournaments is that there is no grace period feature. 

Basically, with grace period active (GM game only, I guess), when a player NMRs the game pauses for half a normal turn so the GM can reach out to that player and pause the game if necessary. For high-stake games, players are scared to play on dippy because they would immediately lose the game if something real-life loses.

After the nonColour SCs I was planning to look at the GM mode features and test/optimize the UX - or at least what I can do -, maybe adding a grace option feature would be a good addition?

Considering martin already made the GM feature, we can harden it a bit and make sure it gets used, right ;)?

**Comment by JorenC** [comment]
I see there is another issue already. Please feel free to close this when you've seen it ;)

**Comment by zond** [comment]
Alright :D
