### ISSUE TITLE
[GM Mode] UX improvement destroyed GM mode

### ISSUE THREAD

**Issue by JorenC** [zond/dipact#287]
@zond you immediately sprung into action to create a better GM mode, but you 'overdid' it.

Actually, currently GM mode is not usable; the Accordion is removed, so after the game starts, the 'pause' etc features are unavailable - you can only open the game, not pause it...
![image](https://user-images.githubusercontent.com/7293081/133153265-8b989810-90f1-42a9-8774-e5d590f6dc58.png)

The fix I would propose is:
1) Remove GM games from the 'My Games' panel.
2) In the side menu, rather than three separate ones, under "My Diplicity" there is one "Game Master Games" list entry, which works the same as current My games list but with only GM games.
3) After creating a GM game, you automatically end up in the "Game Master Games" page. <= _Risk here is that the user never learns how to get here and would 'lose' his game if they didn't see the hamburger menu, but acceptable - GMs are more advanced players anyway_

**Comment by zond** [comment]
OTOH, it's easy to make the accordion appear - and it's already there for staging games IIRC.

**Comment by JorenC** [comment]
Fixed in new feature
