### ISSUE TITLE
Empty home screen for new players

### ISSUE THREAD

**Issue by JorenC** [zond/dipact#29]
When logging in, the home screen should have an empty state with "new game/find game/private game" as expanded options.

I'll design and try to implement.

**Comment by zond** [comment]
I don't understand, isn't that what we have now?

**Comment by JorenC** [comment]
@zond 
We currently have an empty list. You want to have an empty state screen that is welcoming and guiding to new users (who apparently never have played a game before):
https://material.io/design/communication/empty-states.html

It should at least have the options
- Create new game
- Find a (private) game <<< For those coming here to play with friends
- Find public game
- Read the manual / First time playing Diplomacy

**Comment by JorenC** [comment]
![image](https://user-images.githubusercontent.com/7293081/79115970-8d209080-7d87-11ea-94be-bf10b197816d.png)
This is the current home screen when you just enter the game, not very inviting :) (note to self to pick this up, now working on the game lists)

**Comment by JorenC** [comment]
Now implemented new start player screen
