### ISSUE TITLE
Diplicity.com description SUCKS

### ISSUE THREAD

**Issue by JorenC** [zond/dipact#373]
@zond can we add this to our description - either in the server console or the META information (I'm not sure where it goes)

![image](https://user-images.githubusercontent.com/7293081/148702626-4231c8d5-2acf-4a79-907c-a0bb5136eb72.png)

Should be:
A digital version of the famous "Diplomatic" board game, which is all about diplomacy and conquering your friends....

**Comment by zond** [comment]
Fix it by updating https://github.com/zond/dipact/blob/master/web-app/public/index.html#L10 :)

**Comment by johnpooch** [comment]
Just a suggestion:
"A digital version of the classical strategy board game "Diplomacy". Destroy your enemies. Then destroy your friends."

(mainly taken from the description of the app on play store)

@JorenC

**Comment by JorenC** [comment]
Closed. Added the Crossplay reference to the Android app.
