### ISSUE TITLE
"No notification permission" banner

### ISSUE THREAD

**Issue by tetafro** [zond/dipact#452]
I have this message every time I open https://diplicity.com.

> No notification permission. You won't get new message or phase notifications.

Maybe it's better to show the banner only once, or just remove this check at all?

**Comment by JorenC** [comment]
You did not give diplicity access in Chrome to send you notifications. This means you won't get updated/can't play the game (it's like WhatsApp without permissions - it means you won't know if someone sent you a message).

It's critical enough to warn you every time about (and its only a toast) in case you use Android for notifications - people that don't will ruin a game, and there is no way for us to ask again (the site is "banned" from Chrome notifications)

**Comment by JorenC** [comment]
Why don't you join us in the discord?

**Comment by tetafro** [comment]
Ok, thanks. I get your point, will ask more in Discord.
