### ISSUE TITLE
[UX] Snackbars for open orders

### ISSUE THREAD

**Issue by JorenC** [zond/dipact#46]
Currently, the game changes the icon based on the order status (good!)

![image](https://user-images.githubusercontent.com/7293081/78709014-46f4a880-7913-11ea-894c-366382eff395.png)

![image](https://user-images.githubusercontent.com/7293081/78709048-4fe57a00-7913-11ea-9fea-942702b9ab3e.png)

Ideally, we would also show a snackbar when a game is opened:
![image](https://user-images.githubusercontent.com/7293081/78708626-bae28100-7912-11ea-8a41-b33c16bb7d8b.png)

This would open the Orders tab (which will be more explanatory than it currently is)
a) Is a reminder for all players to please @#$#@! go confirm your orders ASAP since we're all waiting on you ;)
b) Is an explanation to vet Dip players where to confirm their orders (since it's not immediately apparent in the GUI)
c) Is an explanation to new Dip players about the concept that they have to confirm their orders

Sandbox here, but I couldn't get it to work in game.js:
https://codesandbox.io/s/material-ui-snack-bar-9xx3d?file=/src/AuthPage.js
Component and API here:
https://material-ui.com/api/snackbar/

**Comment by zond** [comment]
Right, if I write "Might fix #XXX" GitHub decides I actually meant that it DOES fix #XXX.

Anyway, @JorenC will have to decide if it actually DOES fix this one.

**Comment by JorenC** [comment]
Fixed!

**Comment by zond** [comment]
What was that plan you had about "You have provided orders for all your units, don't remember to confirm your orders"-snackbar?

Also - in the commit message I wrote (but forgot to write here): I'm not super happy about the wording. In the orders list I used the wording "Ready for next turn" IIRC, but in the snackbar it's "confirm your orders", it doesn't really match. Can you think of a better way to phrase it, that's both true, simple to understand, and fits the snackbar AND the order list?

I.e. "ready to resolve" isn't necessary for the orders to be processed, it's just that you are "ready to resolve to next phase".

**Comment by JorenC** [comment]
I agree with the wording, but I think the issue can remain open. 

This goes in the complete concept of "Ready for next turn" or "Commit" or "Confirm" or whatever. We need to make sure this concept makes sense overall. 

> What I want to do is that I want to work on the order screen, and not use the current list view (which is quite unclear) but make specific, "hovering" UI that has a commit and draw button + an explanation of what that means. 

For the other players (and reference, I want to use icons rather than checkboxes to show the states for previous turns, since it's only relevant to the observers afterwards. 

When I/we make that GUI for the orders, we will know the correct wording. "Ready for next turn" is good but still a bit too vague, IMO. It seems to "carefree" without signaling that you _should_ commit your orders, unless you really can't...

**Comment by zond** [comment]
Alright, let's just leave it open then :D
