### ISSUE TITLE
Blank screen (beta) 

### ISSUE THREAD

**Issue by GMLM2349** [zond/dipact#470]
![Screenshot_2023-05-13-07-46-15-58_584d755614f39f06b5aa11314185f58c](https://github.com/zond/dipact/assets/62351422/000f8180-b1c2-4d49-a4be-52f10b946a73)
Hey everyone! Just wanted to report a bug in the Beta version. Whenever I open the app, it says "loading Beta..." then shows me this screen and freezes. However, it works just fine on browser.

**Comment by JorenC** [comment]
This should be fixed after we added error boundaries. Now gives an error screen.
