### ISSUE TITLE
A way to improve game queues

### ISSUE THREAD

**Issue by zond** [zond/dipact#50]
We are balancing the game queue wait time with the need for active players at game start by kicking NMR players from all staging games.

This is problematic since the players aren't notified (we have no mechanism for this) and because some games are staging for months, and an NMR during that time might not indicate inactivity.

![YourMyOnlyHope-vblog](https://user-images.githubusercontent.com/7541/78778490-a5fe0000-799b-11ea-8886-d6f578a7c4c8.png)
Help me, @JorenC, you're our only hope.

**Comment by JorenC** [comment]
So I think the solution is easy, the implementation is not. 

1) When a game has enough players, start a "phase 0", during which chat is not yet available.
Send each a "new phase" notification in which they are alerted that the game begins. This notification will tell them that they need to submit orders to confirm they're playing
2) Players clicking the notification will enter the gameview
3) All players entering the game view during this time will get to see a dialog with a welcome to the game, and have them ask to confirm they're playing.
https://material-ui.com/components/dialogs/
4) Once they confirmed they enter the gameview as normal, similar to staging games.
5) Once all players have confirmed, start the new phase (spring 1901).

If some players have not confirmed, move back to open and send everyone a notification that the game will move back to the staging area.

**Comment by zond** [comment]
Subsumed by #154

**Comment by JorenC** [comment]
I think we should reopen this.

We have the feature, but not yet a good UX solution that we can release.

**Comment by zond** [comment]
Yes, but we don't need two issues to track it, right?

**Comment by JorenC** [comment]
No but this one had my more deliberate description and I don't want it to
get lost ^_^

**Comment by zond** [comment]
Fair enough :)
