### ISSUE TITLE
Login: Explanation of the Game (+ Rules)

### ISSUE THREAD

**Issue by JorenC** [zond/dipact#51]
On the login screen, there should be a "scroll down to see the game" for people who are new to the game (e.g. invited by other players to join). 

It should firstly have a quick overview of the game, and then one-by-one explain the game rules. 
This should be a separate React component so we can drag & drop it anywhere we want:
- In the drop-down there can be a "consult the manual" overflow menu.
- It could also be below the "New Game" element as "New to diplomacy?" for people who skipped over it during log in.

>> Do we still need the wiki afterwards or combine it?

**Comment by zond** [comment]
We can keep the wiki as well, that it's publically editable makes it different.
