### ISSUE TITLE
[UX] Order screen restyling

### ISSUE THREAD

**Issue by JorenC** [zond/dipact#53]
The order screen should be revamped. 

Ideally:
- Your own orders are always on top
- There's some colour coding on the nation heading colour
- There are icons rather than checkboxes to display "Committed"/"Draw"/"NMR" (< I had to look that up)
- There is a sticky "Commit" and "Draw" area on the screen when there are orders to give. There is a small explanation about what "Commit" means - subline.

Design TBD

**Comment by zond** [comment]
To clarify, it doesn't say "commit" or "nmr" now, it says "ready for mext turn" and "assumed inactive" :)

**Comment by JorenC** [comment]
I'm going to close this. It's not perfect yet, but good enough for now until we get more feedback.
