### ISSUE TITLE
[Critical] Ask for notification permission only when joining a game

### ISSUE THREAD

**Issue by JorenC** [zond/dipact#58]
Currently, the website asks for permission to send you notifications when you reach the homepage. The default response is to deny it, because you don't know yet whether this app will send you spam. 

Once the user has denied the permission, it's hard (Chrome > Settings > Site setting > dipact > notifications > reset > revisit) to get it back, so you want to get this first time right. 

The best fix would be to wait until the user JOINS, CREATES or VIEWS a game for the first time - the three indicators he will need notifications

**Comment by zond** [comment]
Actually, this needs more fixing. I need to made the messaging start on join/create, not when the game is first viewed - otherwise the user won't know when the game starts.

**Comment by JorenC** [comment]
I thought about it some more. 
It should be on either Join, Create or View.

**Join/Create:** They are intent on starting a game, so they understand why the permission is needed (sort of) and are ready to accept (and, they understand what the site is about and trust it enough to register with their Google account and can understand that it is needed (because of the fact you waited with asking until this moment). This is also in immediate response to their action, so it's logical why you ask and trusted to be not spam.

The reason to add View game would be for players on a new device/reset their permission/coming in from the Android app. They would never create/join, but still need the notifications. Better would be "view a game (**that they are currently in themselves**)" . If it's just "view a game" they might still be exploring and not want any notifications for them at that moment. IF we can check that they are viewing a game THEY ARE IN THEMSELVES that would mean that they are intent on joining the game and it's logical they want notifications.

**Comment by zond** [comment]
Join/create is fixed now. View is not necessary - every time you load the app it will check the server if the messaging _should_ be turned on (you have given permission before), and will turn it on immediately then.

Just viewing a game is not enough to start messaging - you might view games before deciding to play yourself.

On the other hand - now that I added some logic to the messaging system that it shows a snackbar when you deny the notification permission, maybe we should use a dialog explaining why we want it when we start the system, so that users are prepared? @JorenC do you want to define the wording for this? And maybe the wording for what we should say when someone denies it?

**Comment by JorenC** [comment]
I'm a bit hesitant on a dialog for this - maybe we should leave this until we "release". I think on web it's necessary, because you need to grant the notification permission for any website if you want to use the Chrome console > And that's the one I'm targeting. 

For iOS you also need permission but you have no control, I believe. For Android, you have it by default. I'd wait with dialogs until we now more on the situation. If you added it like this, I think we're okay...

OR, CAN you check whether you have permission to publish messages on Chrome?

**Comment by zond** [comment]
I can ask for permission, and see if I succeeded. But an old "no" will just
become a no without asking the user...

**Comment by zond** [comment]
Closing this now, let's open it again if needed.
