### ISSUE TITLE
[Responsiveness] Unread counters don't reset after viewing a channel

### ISSUE THREAD

**Issue by JorenC** [zond/dipact#61]
When a chat channel has unread messages and is closed, the unread message counter doesn't reset. 

This wouldn't necessarily need a new server ping (that would add a couple of seconds of loading time we don't want) but if a channel is closed then we just reset the counter for that channel - as it has just been observed.

This has the downside that technically any new messages that would have been received while the chat was open while scrolling up would be missed, but I think we can risk that edge case.
-- alternatively it would only only reset once the new message line has been on the screen but I think that is a bit too much effort, unless Martin sees it as a coding challenge ;)

**Comment by zond** [comment]
They should now, check if more needs to be done!

**Comment by zond** [comment]
I think this is fixed now.
