### ISSUE TITLE
[UX] Full province names

### ISSUE THREAD

**Issue by JorenC** [zond/dipact#62]
Currently the order screen uses labels as "kie Moves ska". 

This is leftover from when you had to write things on a paper. But, it's not human language and unnecessary confusing for new players, just jargon. 

If users want to use shorthand they can do this, but it shouldn't be forced by the UI

We should change this to full names, so the order sentences form normal, human language. 
UX principle: have the system speak the human language, not the human speak the system language.

**Comment by zond** [comment]
Note: This requires changing the variant definition in https://github.com/zond/godip/blob/2189e9075a5800790498ef097a087ed82959d1bb/variants/common/common.go#L10

**Comment by JorenC** [comment]
This might be also combined with another change: 
The order menu doesn't show results of resolutions...

Ideally, we'd use props here rather than actual text; e.g. currently we show "Moves" but this means the order becomes "kie Moves bud". If we use props on the order, we can style/display it anyway we want (including the order itself, "Kiel moves to Bupapest" and possibly the unit type "Army Kiel moves to Budapest". 

Or even icons.

**Comment by zond** [comment]
We can add the results - for all resolved phases the results are available. The error messages aren't friendly, but they exist :)

**Comment by zond** [comment]
What do you mean by "use props"?

**Comment by JorenC** [comment]
I'm using that if we can add it to a props element, rather than hardcoded text, we can style it correctly in the front end (e.g. icons or specific strings).

Currently, the "order menu" says "CANCEL". But, cancel means cancel your current action (e.g, close the dialog). It should say "CLEAR" as it clears the current order. This is a minor inconvenience, you experience it a couple of times, but these kind of mistakes are really annoying.

I tried to look into this, but it seems the orders are defined in the variant and I can't find out where... 

So, if we add things like full names, order results, orders and pass them along as props (phase.order.origin phase.order.destination, phase.order.type, phase.order.result) something like that, it would make more sense.

**Comment by zond** [comment]
> Currently, the "order menu" says "CANCEL". But, cancel means cancel your current action (e.g, close the dialog). It should say "CLEAR" as it clears the current order. This is a minor inconvenience, you experience it a couple of times, but these kind of mistakes are really annoying.

This should be a separate issue. Or you can fix it at https://github.com/zond/dipact/blob/master/resources/js/dip_map.js#L411 :)

**Comment by zond** [comment]
Otherwise, I agree :)

**Comment by zond** [comment]
This is fixed for Classical. Other variants to follow.

**Comment by JorenC** [comment]
I've just done them for ALL variants. Now doing Redux, then going to
bed.... (lots and LOTS of provinces). Expect a pull request in 20 minutes
or so

**Comment by zond** [comment]
Woot!

**Comment by JorenC** [comment]
https://github.com/zond/godip/pull/86.

@zond can you tell me how I can access them from the client?

**Comment by zond** [comment]
It's inside the variant structure. E.g. https://github.com/zond/dipact/blob/master/resources/js/helpers.js#L1551
