### ISSUE TITLE
[Responsiveness] Delayed loading indicator

### ISSUE THREAD

**Issue by JorenC** [zond/dipact#63]
An app actually BEING fast and APPEARING fast to the user are two things. Currently, the app feels slow because there is a lot of loading.

Especially on the tabs of the game; Also, I think we should do something to make the app feel more responsive. E.g. now, every time you load a tab you get to see the spinner in the foreground... That actually makes the app FEEL really slow, because it looks like you have to wait for it. While actually in the background the app has already loaded but the server is checking for any latest update.

The solution would be to show the map/messages/orders immediately and update them if they're loaded within > X second (you would see a small update happening). Only if the loading would be more than say 4 seconds, you can show the spinner until the site is loaded

Attached an example video where you can see the background load almost instantly but the loader making it feel slow

**Comment by JorenC** [comment]
[Chrome.mp4.zip](https://github.com/zond/dipact/files/4461218/Chrome.mp4.zip)

**Comment by zond** [comment]
More work is done on this now, please see if there is more that needs doing!

**Comment by JorenC** [comment]
This feels so much, much faster. I think we can start applying this principle on other areas as well (e.g. start screen), but when it pops up.
