### ISSUE TITLE
[Responsiveness] Delayed sent message indicator

### ISSUE THREAD

**Issue by JorenC** [zond/dipact#64]
Similar to the loading indicator, I was thinking about sending messages.
1) If you send a message, have the client currently immediately show the message as sent (even though it isn't yet). There can even be a similar indicator as the Whatsapp two checks (one check for sent, one check for received), or a similar small loading indicator that it's still "on the way" (if you want to prevent the edge case of someone IMMEDIATELY closing the browser after pressing send).
2) Send the message in the background.
3) Receive the confirmation the message has been sent
4) Update the small loading indicator OR do not show any change at all (depending on solution for (1)
5) If there is an error, show the message as red after a while.

This is how many chat agents work, and it makes them feel "instant", even though the other party might take up to 10-15 seconds to receive the message...

**Comment by zond** [comment]
Try it now - I made new messages be added before they are sent, with "in progress" instead of a timestamp. Also sending them without a spinner.

**Comment by JorenC** [comment]
Very nice. We need to update the "in progress" indicator, but the idea works really well! Good solution!

**Comment by JorenC** [comment]
(I'm a couple of commits in, only need to create that "DRAW" checkbox somewhere on the order screen, then I'll commit the front end and ask you to connect it. 

Can you change "...in progress..." to "Sending..." (including the capital?)

**Comment by zond** [comment]
Cool :)

Why don't you change it? It's just a string in chat_message.js

**Comment by zond** [comment]
Alright, I was in there and messer around, and updated it to "Sending...".

**Comment by zond** [comment]
I guess this is fixed now.
