### ISSUE TITLE
[UX] Order menu

### ISSUE THREAD

**Issue by JorenC** [zond/dipact#68]
The order menu has "CANCEL" option, which means "cancel your current action - e.g. giving an order - e.g. closing the order dialog'.  However, it actually should say "CLEAR" because it will clear any order given.. Any cancel option should be in the front end, because it depends on how it's delivered.

I tried to find it, but it seems to be defined in the variant, and couldn't find it in godip...

**Comment by zond** [comment]
Oh, you already made it a different issue :D

It's defined at https://github.com/zond/dipact/blob/master/resources/js/dip_map.js#L411
