### ISSUE TITLE
[BUG] Clicking received message notification in chrome opens the JSON

### ISSUE THREAD

**Issue by JorenC** [zond/dipact#79]
It opens this page instead of the actual message channel:
![image](https://user-images.githubusercontent.com/7293081/79570749-506fd480-80ba-11ea-99aa-fe6d0f108497.png)

**Comment by zond** [comment]
That's weird, it works for me :O  

Is this always, or only background or only foreground? And if only foreground, does it happen when you have the chat_channel open?

**Comment by zond** [comment]
Also, could you show me what the JS console says at that time?

Also, could you repeat this after totally cleaning out your cache? Service workers are persistent, and might survive longer than a couple of reloads.

**Comment by JorenC** [comment]
![image](https://user-images.githubusercontent.com/7293081/79586916-13afd780-80d2-11ea-82cb-2ca2c8f5fcf7.png)
This is what the console says... The notification moves up on the front...

**Comment by zond** [comment]
Super weird, it works perfectly for me, and I have no idea what could cause it to actually load the service worker.

**Comment by zond** [comment]
I think I found it. Just rolled out again. Reload the service worker and try again!

**Comment by JorenC** [comment]
Resolved, checked, closed!

**Comment by zond** [comment]
Nice! The fix was simple once I understood web workers better :)
