### ISSUE TITLE
End game screen

### ISSUE THREAD

**Issue by JorenC** [zond/dipact#90]
After closing the score menu, we should highlight this when a game has ended. Maybe add the rank.

**Comment by zond** [comment]
How do you mean?

I just pushed a change that shows the rating effects of a game to the result screen. Was that part of what you wanted?

**Comment by JorenC** [comment]
I think
1) There should be a different between finished games and normal games. Now, a finished games looks like an ongoing almost abandoned game. Having some kind end state would make it feel more finished and "done".  (also because they have a "current phase".

2) There is no "confirmation" of the winner. Of course you know a solo win, but there is never a "well done" confirmation, celebrating the winner. Even a "draw" state is not really announced. Also here, an end-game state would confirm that a game is finished, not just because it appears in your "finished" list.

3) There is no salience for the reward system. If we show/tell users how many points they earned and who won, then it becomes more intuitive to understanding that there is a point system and how it worked. 

4) By showing how the game proceeded, it's also a nice recapture of the progress of (yourself) through the game, and where the critical "objective" tipping point was.

In other games, it's normal to have a "end game stats screen":
![image](https://user-images.githubusercontent.com/7293081/79850152-c9757180-83c3-11ea-9d3a-387ae3f1f2ad.png)

The solution I was thinking of was to have a dialog (similar to the one we have now for the points)  pop up when loading a finished game, with a dismiss button. There would be some minor changes (e.g. show the winner, result etc). 

The risk is that someone wants to visit a finished game very often, and get annoyed by the extra click, but I doubt that that's a common use case (you visit them once in a while for reference MAYBE). However, for all players it creates a solid "the game has ended and this is the result" ending.

**Comment by zond** [comment]
It sounds like we need to unify the "scores" and "results" screens into something more rewarding and salient. I assume you have ideas? :D

**Comment by JorenC** [comment]
exactly. I'll look at it when I have time...

**Comment by zond** [comment]
👍

**Comment by zond** [comment]
Is this closeable, or do you want to improve it more?

**Comment by JorenC** [comment]
I think it's okay, but I am considering showing the dialog instead of the snackbar when you open an old game. What do you think?

If you think that's too much, close it

**Comment by zond** [comment]
I'm fine with what you prefer :)

**Comment by JorenC** [comment]
In that case, can we show the dialog when the screen ends instead of the
snackbar?

Should I make it or can you?

**Comment by zond** [comment]
I can do it.

**Comment by zond** [comment]
This is done, reopen if necessary
