### ISSUE TITLE
[UX] Create tutorial for new players based on Lab mode

### ISSUE THREAD

**Issue by JorenC** [zond/dipact#94]
Lab mode allows us to create a simple tutorial to get new players onboard with the game

**Comment by zond** [comment]
Oooh, I like how you think!

**Comment by JorenC** [comment]
On the login screen, there should be a "scroll down to see the game" for people who are new to the game (e.g. invited by other players to join).

It should firstly have a quick overview of the game, and then one-by-one explain the game rules.
This should be a separate React component so we can drag & drop it anywhere we want:

In the drop-down there can be a "consult the manual" overflow menu.
It could also be below the "New Game" element as "New to diplomacy?" for people who skipped over it during log in.


We can keep this as one issue. New players is a WHOLE new feature to work on.

**Comment by JorenC** [comment]
I'm closing this with the new 'tutorial' on notion, as it's the best ROI for now. 
- Added it to the notion update page
- Added a link to it on the game.js menu 
- Made game.js show a settings icon rather than three dots so people are more likely to click it - and find it. 

Interactive tutorial is still nice, but maybe in the future-future.
